apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j4-neo4j-plugins
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/minikube/data/neo4j4-neo4j-plugins"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j4-neo4j-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/minikube/data/neo4j4-neo4j-data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j4-neo4j-backup
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/minikube/data/neo4j4-neo4j-backup"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j5-neo4j-plugins
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/minikube/data/neo4j5-neo4j-plugins"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j5-neo4j-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/minikube/data/neo4j5-neo4j-data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j5-neo4j-backup
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/minikube/data/neo4j5-neo4j-backup"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j5-backup-neo4j-plugins
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/minikube/data/neo4j5-backup-neo4j-plugins"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j5-backup-neo4j-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/minikube/data/neo4j5-backup-neo4j-data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: neo4j5-backup-neo4j-backup
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/minikube/data/neo4j5-backup-neo4j-backup"